**Tensors**

1) In PyTorch, tensors have a similar data structure as arrays in NumPy.
2) In PyTorch, we use tensors to encode the input and output of the model as well as the parameters of the algorithm.
3) Tensors are similar to arrays, but the main difference is that NumPy arrays work only on CPU, while tensors can be moved to the GPU to increase computational speed.
4) Tensors in PyTorch are multi-dimensional arrays with GPU support and automatic differentiation capabilities, used for inputs, outputs, and model parameters.

**install torch**


In [5]:
pip install torch   

Note: you may need to restart the kernel to use updated packages.


In [6]:
#import torch and numpy
import torch
import numpy as np




**How to initilize Tensors**

There are various ways to initilize the tensors
1) Directly From Data
2) From a numpy array
3) From another tensor
4) With random or constant values
   

In [9]:
#Directly From Data
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [11]:
#From a numpy array
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [14]:
#From another tensor
#The new tensor will retain the properties and characteristicss of the old tensors otherwise it will be overwritten explixity.

x_ones=torch.ones_like(x_data)# retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand=torch.rand_like(x_data,dtype=torch.float)# overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3886, 0.5850],
        [0.2610, 0.7266]]) 



In [20]:
#With random or constant values:
shape=(2,3)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_torch=torch.zeros(shape)

#Print
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_torch}")

Random Tensor: 
 tensor([[0.2062, 0.5491, 0.0418],
        [0.4729, 0.4999, 0.3414]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])




**Tensor Attribute**

Tensor attribute describe there shape, datatype, on which machine they are stored(CPU OR GPU)


In [24]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu



**Tensor Operation**

Tensors perform more than 100 operation.Some of important operations include indexing, slicing, mathematical operations
linear algebra, random sampling etc.




In [27]:
# We move our tensor to the GPU if available otherwise it will use cpu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
print(f"Running on device: {device}")


Running on device: cpu




Try some of the features of the Pytoch

In [32]:
#Standard numpy-like indexing and slicing:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [33]:
# Multiplying tensors
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [34]:
# In complex mathematical problem in your reseach you need to write a program to multiply two matrix. How can we do this using pytoch?
# We can do this in the following way
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [41]:
# How can we change numpy array into torch arrays
n = np.ones(5)
t = torch.from_numpy(n)

print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
